CREATE DATABASE IF NOT EXISTS BRODAHUT;
USE BRODAHUT;

-- Create dbadmin user
CREATE USER IF NOT EXISTS 'dbadmin'@'%' IDENTIFIED BY 'br0d4hut';
GRANT ALL PRIVILEGES ON BRODAHUT.* TO 'dbadmin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;